//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_Hog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependency
    {
        public int DependencyID { get; set; }
        public int TicketID { get; set; }
        public int DependentTicketID { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Ticket Ticket1 { get; set; }
    }
}
